deed_type = {
  "ABAN": "Abandonment of Street or Alley",
  "ADMD": "Administrator's Deed",
  "AFF": "Affidavit Death Joint Tenant",
  "AGRE": "Agreement or Contract of Sale",
  "ANNX": "Annexation of Parcel",
  "ASSG": "Assignment of Agreement/Contract (Buyer to Buyer)",
  "BLA": "Boundary Line Adjustment",
  "CERT": "Certificate of Sale",
  "COMB": "Combination of parcels",
  "CORR": "Correction Deed/Etc.",
  "CREA": "Create parcel - Not previously Assessed",
  "DECR": "Decree of Court",
  "DEDM": "Dedication Tract Map",
  "DEED": "Deed",
  "DEF": "Trustees Deed Upon Sale",
  "DESC": "Deed to mapping to check legal description",
  "DLM": "Divison of Land Map into large parcels",
  "EXEC": "Executor's Deed",
  "F#": "File Number",
  "FTIN": "Future Interest NRS 111.109",
  "FTRV": "Future Interest Revoked NRS 111.697",
  "GIFT": "Gift Deed",
  "IMPK": "IMPROVEMENT ACCOUNT KILLED",
  "LIEU": "Deed In Lieu of Foreclosure",
  "LPAT": "LAND PATENT",
  "MERG": "Merger Company Name Change",
  "NA": "No Action File #",
  "ORDR": "Court Order",
  "OWNR": "Owner Requests Name Change",
  "PM": "Parcel Map",
  "QC": "Quitclaim Deed",
  "RECV": "Receivership",
  "REIN": "REINSTATE PARCEL BOUNDARY LINES",
  "RESC": "Rescission of Foreclosure",
  "REST": "Resolution Transfer - Accepting Parcels",
  "REVP": "Reversion Parcel Map",
  "REVT": "Reversion Tract Map",
  "RMAP": "REMAP",
  "SHER": "Sheriff's Deed upon Sale",
  "SPDW": "Deed held for new split pending",
  "SPLT": "Split Memo",
  "STCT": "Street Cut",
  "STKL": "Street Dedication (Kill)",
  "STRJ": "STREET RESOLUTION DEDICATION REJECTED",
  "STTR": "Street Transfer from Dedication or Resolution",
  "SUB": "Subdivision Tract Map",
  "TAXD": "TAX DEED (TO TREASURER TRUSTEE)",
  "TAXR": "TAX RECONVEYANCE (TAXES PAID)",
  "UC": "Under Contract (Seller to Buyer)",
    "1G": "Good Verified Sale",
  "1GCA": "Good - Adjusted",
  "1GCR": "Good Conditional (See Remarks)",
  "1GLC": "Land Use Change After Sale-See Notes for Adj",
  "1MGA": "Multiple Parcel",
  "1MGH": "Good Adjusted Multiple Parcel Sale",
  "1SVR": "Sales Verification Letter",
  "2D": "Sale Price Verified By Declaration of Value",
  "2F": "Valid Sale after Foreclosure",
  "2MD": "Multi Parcel Declaration",
  "2MF": "Multiple Parcel Valid Foreclosure Sale",
  "2MQC": "Multiple Parcel Conditional (mixed use)",
  "2MSV": "Multiple Parcel SVL",
  "2QC": "Verified With Questionable Conditions",
  "2SVL": "Do Not Use This Code",
  "2TBV": "To Be Verified By Appraisal",
  "2XD": "Excluded Sale With Declaration",
  "3B": "Do Not Use This Code",
  "3BCK": "Legal description needs to be checked",
  "3BCT": "Clearing Title (clarifiying vesting",
  "3BDS": "Do Not Use This Code",
  "3BEA": "Change Of Etals Only (Add Or Delete)",
  "3BF": "Foreclosure",
  "3BFI": "Interest conveyed in the future at owners death",
  "3BFM": "Transfer Between Family Members",
  "3BGG": "Grantee-Grantor the Same",
  "3BIT": "Intermediary Transfer",
  "3BO": "Other Conditions (see remarks)",
  "3BSP": "Describes non existent parcel",
  "3MB": "Multi Parcel",
  "3MNT": "Multi Parcel No Transfer Tax",
  "3NTT": "No Transfer Tax",
  "4BV": "To Be Verified Transferred RP to Sales",
  "4MV": "To Be Verified Transferred AP To Sales Multi Parcel",
  "4V": "Do Not Use This Code"
}
